# Plots van Biasrisico

Harrie: Dit hoofdstuk wordt nog aangepast.

Dit hoofdstuk is geschreven door Luke A. McGuinness (McGuinness, L. A. (2021). Risk of Bias Plots. In Harrer, M., Cuijpers, P., Furukawa, T.A., & Ebert, D.D., *Doing Meta-Analysis with R: A Hands-On Guide* (online version). bookdown.org/MathiasHarrer/Doing_Meta_Analysis_in_R/rob-plots.html. )

```{r}
# Load the required package
library(robvis)
library(tidyverse)
```

```{r}
data_robins<-data_robins
glimpse(data_robins)
```

```{r}
rob_summary(data = data_rob2, 
            tool = "ROB2")
```

```{r}
rob_summary(data = data_robins, 
            tool = "ROBINS-I")
```

```{r}
rob_summary(data = data_robins, 
            tool = "ROBINS-I")
```

```{r}
rob_summary(data = data_quadas, 
            tool = "QUADAS-2")
```


```{r}
rob_summary(data = data_rob2, 
            tool = "ROB2", 
            overall = TRUE)
```

```{r}
rob_summary(data = data_rob2, 
            tool = "ROB2")
```

```{r}
rob_summary(data = data_rob2, 
            tool = "ROB2",
            weighted = FALSE)
```

